plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'

    id 'kotlin-parcelize'
}

android {
    namespace "com.meshenger.backend.network"
    compileSdk 34
    defaultConfig {
        minSdk 26
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "com.squareup.okio:okio:3.17.0"
    implementation project(":backend:security_native")
    implementation project(":backend:transport2")
    implementation "com.google.crypto.tink:tink-android:1.12.0"

    androidTestImplementation "androidx.test:runner:1.5.2"
    androidTestImplementation "androidx.test.ext:junit:1.1.5"
    androidTestImplementation "androidx.test:rules:1.5.0"
}
